### ISSUE TITLE
[BUG] Issue with combination of zoom in + drag + click on PDF results in PDF setting position in bottom-right corner

### ISSUE THREAD

**Issue by tarikt-hybird** [BetterTyped/react-zoom-pan-pinch#336]
This issue can be reproduced even on your official documentation demo. 
You can use this URI: https://prc5.github.io/react-zoom-pan-pinch/?path=/story/examples-svg-zoom-to-element--svg-zoom-to-element 

🐛 How to reproduce it? 

1. Zoom into the PDF (either by double click or using the scroll)
2. Drag/move along the PDF in any way
3. Click on random positions on the PDF

Results in:
- The PDF coordinates/camera/position is moved to the bottom-right corner of the PDF.

My environment and dependencies:

- react - v16.8.6
- react-pdf - v5.7.1
- react-zoom-pan-pinch - v2.1.3

I have been able to reproduce this issue on all minor versions since > v2.1.* all the way to the latest (v2.5.0)

**Comment by coolneo4u** [comment]
Even without drag, if I zoom in, then move mouse and click, it pans image to random direction.
You can reproduce it on official document demo: https://prc5.github.io/react-zoom-pan-pinch/?path=/story/examples-small-image--small-image

https://github.com/prc5/react-zoom-pan-pinch/assets/6052933/685721a6-664b-4dbd-a611-58796b267778

**Comment by psychopathh** [comment]
+

**Comment by k2xl** [comment]
any updates/workarounds for this issue?

**Comment by tarikt-hybird** [comment]
Update: managed to resolve it by disabling the `velocityDisabled` property inside the panning object. 
Code: 

```
panning={{
          lockAxisX: false,
          lockAxisY: false,
          velocityDisabled: true,
}}
```

version: `"3.1.0"`

Hope this helps!
