### ISSUE TITLE
[Bug] Panning activationKeys

### ISSUE THREAD

**Issue by Sergii5854** [BetterTyped/react-zoom-pan-pinch#375]
I would like to use the pan with functional keys such as Alt, Shift, Ctrl, Cmd.
The pan should be triggered by using CTRL+Click or CMD + Click. 

Could you please advise me on how I can use functional keys?

**Comment by jCrip** [comment]
use it like this:

`<TransformWrapper
            panning={{ activationKeys: ['Alt'] }}
>

//your code
</TransformWrapper>
`
