### ISSUE TITLE
Double click mode: Toggle zoom

### ISSUE THREAD

**Issue by Cretezy** [BetterTyped/react-zoom-pan-pinch#409]
**Is your feature request related to a problem? Please describe.**

We would like a double click mode where it zooms in when not zoomed, and zooms out when zoomed in.

**Describe the solution you'd like**

`doubleClick={{ mode: "toggle" }}` 

**Describe alternatives you've considered**

Unfortunately it doesn't seem possible with the library directly, but catching `onDoubleClick` in the element, we can emulate the behavior with `useControls`.

---

Opened PR: https://github.com/prc5/react-zoom-pan-pinch/pull/410

**Comment by marisaroque** [comment]
Any news about this?
