### ISSUE TITLE
with react-slick on mobile react-zoom-pan-pinch next prev not working with zoom effect

### ISSUE THREAD

**Issue by arvind-netzwelt** [BetterTyped/react-zoom-pan-pinch#501]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LakshayySharma** [comment]
@arvind-netzwelt Can you provide a code snippet showing the issue which you are facing as there is not sufficient information. 

Only on the basis of present information, I assume you are facing issue regarding scrolling to next image while in zoomed state in react slick. If you want to go to next and or previous image you can do this programmatically. You can use "onPanning" function of react-zoom-pan-pinch to check if you have reached the left or right boundary of your image while panning and can't pan further. Then if it's true you can use "slickGoTo/ slickNext/ slickPrev" functions of react-slick to trigger scrolling to next or previous image

**Comment by hk-skit** [comment]
@LakshayySharma It would be very helpful if you can share the reference document or sample code snippet to detect whether we are on boundaries. We are using react-zoom-pan-pinch with embla carousel. Could find any document to for events like panning.

TIA
