### ISSUE TITLE
Panning Not Working within iframe — Events Not Captured

### ISSUE THREAD

**Issue by manish-taygo** [BetterTyped/react-zoom-pan-pinch#504]
I am encountering an issue when using it inside an iframe. Specifically, the panning functionality does not work as expected because the library is not capturing mouse events within the iframe. It appears that react-zoom-pan-pinch is only listening to mouse events from the parent window and not from the iframe.

**Steps to Reproduce:**

1. Create a react-zoom-pan-pinch setup inside an iframe.
2. Attempt to pan the content within the iframe by dragging the mouse.
3. Observe that panning does not work, and no events are captured.

**Expected Behavior:**

The panning functionality should work within the iframe, capturing mouse events inside the iframe and updating the pan state accordingly.

**Comment by MaziyarMK** [comment]
@manish-taygo did you just added non-passive event dispatches to solve this on your own?
